version: '3'

services:
    nginx:
        image: nginx:1.15-alpine
        container_name: nginx
        hostname: nginxo
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./certs:/etc/certs
            - ./nginx:/etc/nginx/conf.d
            - ./nginx/logs:/var/log/nginx
    
    ## Portainer - Docker visualisation and management
    portainer:
        image: portainer/portainer
        container_name: portainer
        hostname: portainer
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes
            - portainer_data:/data
        networks:
            - default
            - core_default

    ## PG Admin 4 - SQL explorer and Visualization
    pgadmin:
        image: dpage/pgadmin4:4.24
        hostname: pgadmin
        container_name: pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin@harrison.com
            PGADMIN_DEFAULT_PASSWORD: yvgqen8r4VpAuQegP9NurPFPvePQVE
            PGADMIN_LISTEN_PORT: 80
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        networks:
            - default
            - core_default
                
    ## json-server - mock server for simple testing
    json-server:
        image: node:alpine
        hostname: json-server
        container_name: json-server
        command: npx json-server --watch db.json --port 80 --host 0.0.0.0
        working_dir: /home/json-server
        expose:
            - "80"
        volumes:
          - ./json-server:/home/json-server
        networks:
            - default

                    
volumes:
    pgadmin-data:
    portainer_data:

networks:
    # Smart-VUE core network
    core_default:
        external: true

        