version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    restart: always
    hostname: nginx

    volumes:
      - ./certs:/etc/certs
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx

    ports:
      - '80:80'
      - '443:443'

  ## Portainer - Docker visualisation and management
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always

    hostname: portainer
    networks:
      - default
      - shared

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - portainer-data:/data


  ## PG Admin 4 - SQL explorer and Visualization
  pgadmin:
    image: dpage/pgadmin4:4.24
    container_name: pgadmin
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@harrison.io
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80

    hostname: pgadmin
    networks:
      - default
      - shared
      
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  ## json-server - mock server for simple testing
  mock:
    image: node:alpine
    hostname: mock
    container_name: json-server-mock
    command: npx json-server --watch db.json --port 80 --host 0.0.0.0
    working_dir: /home/json-server

    expose:
      - '80'

    volumes:
      - ./json-server:/home/json-server

volumes:
  pgadmin-data:
    name: pgadmin-data
  portainer-data:
    name: portainer-data

networks:
  default:
    name: dev-tools

  shared:
    external: true
