version: '3.9'

services:
  openldap:
    image: bitnami/openldap:2
    hostname: openldap
    container_name: ldap

    ports:
      - 1389:1389
      - 1636:1636

    environment:
      LDAP_ROOT: dc=ana,dc=dev
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: changeme
      ALLOW_EMPTY_PASSWORD: 'yes'

    networks:
      - ldap

    volumes:
      - openldap-data:/bitnami/openldap

  postgres:
    image: postgres
    restart: always
    hostname: postgres
    container_name: postgres

    ports:
      - 5432:5432

    networks:
      - default

    volumes:
      - postgres-data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}

networks:
  default:
    name: shared

  ldap:
    name: ldap

volumes:
  postgres-data:
    name: postgres-data

  openldap-data:
    name: openldap-data
