version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    hostname: postgres
    container_name: postgres

    ports:
      - 5432:5432

    networks:
      - shared

    volumes:
      - postgres-data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}

networks:
  default:
    name: shared

volumes:
  postgres-data:
    name: postgres-data
